### ISSUE TITLE
Possible error in `lambda` funtion (`λ`)

### ISSUE THREAD

**Issue by josecelano** [jeremy-rifkin/mandelbrot-orbits#1]
Following Pr. Robert L. Benedetto's [slides](https://rlbenedetto.people.amherst.edu/talks/mhc_ug14.pdf):

![image](https://user-images.githubusercontent.com/58816/181597204-40cc8b88-0a75-482b-a516-63396ddb3e31.png)

I think the [λ function](https://github.com/jeremy-rifkin/mandelbrot-orbits/blob/master/src/main.cpp#L97) should be:

```c++
std::complex<fp> lambda(const int n, const std::complex<fp> z, const std::complex<fp> c) {
	std::complex<fp> lambda = phi_prime(c, c);
	for(int i = 1; i < n; i++) {
		lambda *= phi_prime(phi_n(i, z, c), c);
	}
	return lambda;
}
```

instead of:

```c++
std::complex<fp> lambda(const int n, const std::complex<fp> z, const std::complex<fp> c) {
	std::complex<fp> lambda = phi_prime(z, c);
	for(int i = 1; i < n; i++) {
		lambda *= phi_prime(phi_n(i, z, c), c);
	}
	return lambda;
}
```

On [line](https://github.com/jeremy-rifkin/mandelbrot-orbits/blob/master/src/main.cpp#L97) `std::complex<fp> lambda = phi_prime(z, c);`. [Link to line](https://github.com/jeremy-rifkin/mandelbrot-orbits/blob/master/src/main.cpp#L97).

Am I right?

I was able to improve the final result (or at least it makes more sense) on my Rust [version](https://github.com/josecelano/mandelbrot-orbits-rust/pull/8).

**Comment by jeremy-rifkin** [comment]
Thank you for opening this issue, it is not the case that it should be `phi_prime(c, c);`. This is an analytical method that's operates on the point `z` converged to during the escape time calculation rather than initial starting point `c`.

When I plug in `phi_prime(c, c);` I get something similar to what you're getting on your project 
![image](https://user-images.githubusercontent.com/51220084/181855300-fb2e33e0-b32a-4099-8f7e-424061ff4966.png)

I'll elaborate more on the PR in the other repo
